### ISSUE TITLE
Session Attachments & Media Aren't E2EE

### ISSUE THREAD

**Issue by M9fJx5UJarnDjHdfNZoz** [Perelandra0x309/secure-im#102]
SESSION USER 1:
All messages are encrypted including multimedia? (Video, documents, etc)

SESSION OPEN GROUP CHAT ADMIN:
Yes, everything is encrypted, not end-to-end in the case of open groups and attachments/multimedia, but everything is onion routed and encrypted.

SESSION USER 2:
[Message 1] Attachments and media aren't e2ee in 1-1 chats / closed groups?
[Message 2] Or attachments and media in open groups aren't e2ee? Bit confused

SESSION OPEN GROUP CHAT ADMIN:
[Replied to message 1] No, not yet, there is still a central server run by the foundation for those, the migration to Lokinet will allow for the implementation of p2p file transfers, so this won't be forever like this, but it's the most practical solution currently, everything is still encrypted and onion routed, but the reliance on a central server for this is not optimal, I agree.
[Replied to message 2] Nothing in regards to open groups is end to end encrypted, open groups are hosted on a single server, most of them by the community, attachments are stored on the open group server, all messages and attachments sent in an open group are still sent encrypted and using onion routing.
Hope that clears up your confusion.

SESSION USER 2:
My concern is less about centralization and more about the encryption standard used. I'm assuming all encryption is done on the user's device so why have asymmetric (/client side) encryption for sending attachments? Surely it's no extra cost to Session's network to handle the transportation of e2ee attachments rather than asymmetrically encrypted attachments?
So, in response to someone writing earlier about how Session isn't protecting against child porn, there is technically, at present, a way to recover the media being sent via Session, just not the text messages?
Can Session call itself an end-to-end encrypted messaging app without clarifying to its users that attachments aren't actually e2ee? This marketing seems unfair to those with relevant threat models.
https://docs.oxen.io/products-built-on-oxen/session/attachments

Quoting directly from https://docs.oxen.io/products-built-on-oxen/session/attachments

"Although service nodes have the ability to store data on behalf of clients, this responsibility only extends so far. Requiring service nodes to store attachments, which can easily be orders of magnitude larger than messages (and might need to be stored for longer periods of time) would place an undue burden on the service node network.

With this in mind, a logical solution is for Session to interface with an untrusted centralised server that stores data obliviously. As long as the central server cannot know the contents of files, or who is storing and requesting the files, this system does not cause any metadata leakage.

This is achieved by first padding each attachment to fit within a fixed number of constant sizes between 0 and 10 megabytes, then encrypting the attachment with a random symmetric AES key. The sender then uploads the encrypted file using an onion request. In response, the file server provides a link to the piece of content, returned via the onion request path.

Once the sender obtains this link, they then send a message to the recipient via an existing pairwise session. This message contains a link to the content, a hash of the content, and the decryption key. The recipient then uses an onion request to pull the encrypted attachment from the centralised file server and decrypt it locally using the decryption key provided by the sender. The recipient also checks the hash against the attachment, ensuring the file has not been modified in transit.

By default, all Session clients use a Session file server run by the Oxen Privacy Tech Foundation for attachment sending and storage. Since attachments are not considered a core feature of Session, this design is in keeping with Session's design principles. The file server is fully open-source, with setup instructions provided so that users are able to set up their own file server. In an upcoming update will be able to specify in the Session client which file server they want to use for attachment sending functionality. This is important both for providing users with choice and control, and ensuring the continued usefulness and functionality of Session if the OPTF were no longer able to maintain the default Session file server."

**Comment by Perelandra0x309** [comment]
Attachments are end to end encrypted, they just aren't peer to peer yet. AS it says:

> Once the sender obtains this link, they then send a message to the recipient via an existing pairwise session. This message contains a link to the content, a hash of the content, and the decryption key.

They key is not sent to the server hosting the file, so the server cannot decrypt the file.  The device that is sending the file encrypts it, then uploads it to the server.  Then it send the link to the file and the decryption to P2P to the recipient.  The recipient then downloads the file and decrypts it with the key.  So only the endpoints are able to decrypt the data.

I will keep this open though because I do need to update my review a bit, so I might include some of this info to update on the development of this service.

**Comment by M9fJx5UJarnDjHdfNZoz** [comment]
Thank you for your response.
I still have some concerns over the type(s) of encryption used for media and attachments.
When I refer to e2ee I guess what I mean (or meant) is public key cryptography of some sort, not symmetric encryption which I generally perceive to be weaker than public key, though of course this varies depending on the key(s) used and the algorithm used.

Perhaps the strength of their symmetric encryption, or the length/strength of the decryption key, is designed to be as secure and unguessable, or with the same level of entropy, as their own public key cryptography method which they use for their text messages. If that's the case then perhaps the symmetric method of encryption is excusable?

A Session open group chat admin recently wrote:
"Attachments in closed groups and one-on-one chats use symmetric encryption afaik since they're still stored on a server run by the foundation, the decryption key and location of the attachment is then sent via public key encryption like the regular text messages."

The following is a quote from https://getsession.org/faq
 > "Messages"
  > "Can I share attachments with my contacts? Does the app strip metadata from those attachments?"

"Session can send files, images and other attachments up to 10MB in both person-to-person conversations and group chats. By default, Session uses the Oxen File Server for attachment sending and storage. The Oxen File Server is an open-source file server run by the Oxen Privacy Tech Foundation — the creators of Session. **When you send an attachment, the file is symmetrically encrypted on the device and then sent to the Oxen File Server**. To send the attachment to a friend, Session sends them an encrypted message containing the link, plus the decryption key for the file. This ensures that the Oxen File Server can never see the contents of files being uploaded to it.

Additionally, Session used proxy routing (soon to be onion routing) to hide users’ IP addresses when uploading or downloading attachments from the Oxen File Server. In future, you will be able to configure the Session app to use a custom file server, such as a self-hosted server or VPS (Virtual Private Server), if you would prefer not to use a file server hosted by the OPTF."

So it seems, to me at least, that public key cryptography isn't utilised (in the standard way that we all know and love and would have expected) for attachments and media in Session.

While I don't fully know how Session operates in group chats, perhaps this use of symmetric encryption for attachments and media is to reduce server storage, by storing one encrypted item intended to be delivered to multiple individuals where the recipients all share the same (and supposedly one-time) key to decrypt the file. Eg in a group of 10 people, the server storage is a tenth of what would be necessary for public key cryptography.

Though, for me, saving space isn't a good enough reason to sneakily downgrade security from public key encryption to symmetric while still calling it e2e and expecting the majority of users to assume public key is used across all of Session's features. Again, depending on the algorithms and keys used, this might not be a downgrade at all but something still doesn't sit right.
I think it needs a little more transparency.

**Comment by Perelandra0x309** [comment]
E2EE is possible even with symmetric key use.  Usually this does involve a public key infrastructure which is used for the two parties to negotiate a connection.  Then once the asymmetric keys are established, a symmetric key is exchanged for use when encrypting and decrypting messages or files sent between them.

In the specific case of Session I believe you are correct that one of the reasons they use symmetric keys for attachments is to save space needed to store the file.  Everyone receiving the file can use the same symmetric key, so only one encrypted version of the file is needed.

There are other reasons in general to use symmetric keys, especially for files.  Symmetric encryption is usually faster than asymmetric encryption.  This is because many of the variations of AES are a block cipher, which means each block of data in the file can be decrypted without needing any of the other blocks to be previously decrypted.  So you can spawn many threads/processes to decrypt several sections of the file simultaneously.  This is not possible with most asymmetric encryption which are usually stream ciphers, which means the first block is decrypted, then the output of that is used as an input for the decryption of the next block.  So this is slower because only one decryption can be done at a time.

Another reason is that AES is actually a very robust encryption system and hard to crack with brute force processing.  Also it is very easy create new symmetric keys for every file or message that is sent.  So even if one symmetric key is broken (very unlikely) it will only work on one file and you need to start brute forcing again for the next file.

Those are the reasons I can think of off hand.  I would not call using symmetric encryption a downgrade from public key encryption.  If you choose a weak symmetric encryption method then yes it could be by using proven AES or something similar it is not a downgrade.

But this is a good discussion and I will use some of our contemplation here to pose some ideas in my updated review.

**Comment by Perelandra0x309** [comment]
Made a note about attachments in my updated review.
