### ISSUE TITLE
Signal no longer supports encrypted SMS

### ISSUE THREAD

**Issue by johnbaitsyou** [Perelandra0x309/secure-im#13]
> Signal
> OK let's get this one out of the way first. If you have a phone, there's almost no way to get away from SMS. _**So the best thing you can do is protect your SMS messages at rest with encryption**_. Signal also offers excellent end to end encryption between Signal users. One draw back of Signal is that everyone you connect with will know your phone number. For people you are comfortable knowing your phone number that is fine, but for those you don't want to give out your number to...
> 

**signal can't send encrypted SMS** messages anymore, you can use a **fork of signal** that focuses on encrypted sms messages **called silence** https://silence.im/
source: https://signal.org/blog/goodbye-encrypted-sms/

**Comment by Perelandra0x309** [comment]
What I mean by "at rest with encryption" is the message data is encrypted in the Signal database on the phone.  Other SMS apps save your messages in plain text when they are saved on the phone. I am not referring to the actual sending of SMS messages, just how they are saved to disk on the phone.

I could perhaps give  runners up nod to Silence, because it does also encrypt at rest and sends encrypted SMS messages (to other Silence users).  But given a choice a would prefer Signal to Signal message encryption over Silence to Silence message encryption because Silence still uses the SMS communications channel which is open to easier hacking. That's one of the reason sited in the Signal blog post to get away from encrypted SMS.

**Comment by Perelandra0x309** [comment]
Added Silence as runner up to Signal
