### ISSUE TITLE
Threema PFS

### ISSUE THREAD

**Issue by temporarium** [Perelandra0x309/secure-im#52]
As per [https://threema.ch/en/blog/posts/why-is-threema-that-secure](url), Threema _does_ have perfect forward secrecy. Your info seems to imply it doesn't. Or am I missing something?

**Comment by Perelandra0x309** [comment]
Temporarium,
See the white paper link on that same website, on page 3 it shows the TLS connection which is not end to end.
It only has PFS while being transported across the internet through a TLS connection, not while at rest on the server or on the devices.  The end to end message encryption protocol itself does not provide PFS.  Pretty much every connection over the internet now uses TLS so in effect every app now has PFS while in transport.  However it could be possible for someone to be listening or access the data on a server during which it is no longer in a TLS tunnel.  If you had a man in the middle attack, that would also negate any TLS encryption since the attacker would have control of the TLS keys.
So I think disregarding standard TLS encryption (which is not end to end, only temporal client/server communication) is fair.

**Comment by temporarium** [comment]
Thank you for answering. You obviously did your research!

But, if the contact is "three-green-dots-verified", then it eliminates the possibility of a man in the middle attack, right? So, just as secure as if it had PFS?

**Comment by Perelandra0x309** [comment]
Hmm, I will have to think about that.  The green just means that at some point in time you physically met with the person to scan the QR code that is generated by their phone app, so this means that you have a very high level of trust that the key is theirs.  (As an aside, yes it is possible to send your QR code as a picture and someone can scan it to "verify" your key without physically meeting you.  But that is not the intended use.)

In reading the White Paper again I also found this section:

> Forward Secrecy
> Due to the inherently asynchronous nature of mobile messengers, providing reliable Forward Secrecy on the
> end-to-end layer is difficult. Key negotiation for a new chat session would require the other party to be online
> before the first message can be sent. Experimental schemes like caching pre-generated temporary keys from
> the clients on the servers increase the server and protocol complexity, leading to lower reliability and more
> potential for mistakes that impact security. The user experience can also be diminished by events that are not
> under the control of the sender, for example when the recipient loses their phone’s data, and along with it the
> ephemeral keys. Due to these and the following considerations, Threema has implemented Forward Secrecy
> on the transport layer only:
> • Reliability is very important to ensure that users do not feel negatively impacted by the cryptography.
> • The risk of eavesdropping on any path through the Internet between the sender and the server, or between the server and the recipient, is orders of magnitude greater than the risk of eavesdropping on
> the server itself.
> With Threema’s implementation, an attacker who has captured and stored the network traffic between a
> client and a Threema server will not be able to decrypt it even if he learns the private key of the server or the
> client afterwards.

I also noticed another link at the bottom of the first link you mentioned, I had not seen this before.  It also demonstrates that you only have one private key that never rotates and always stays the same:
https://threema.ch/validation/

Yeah, so if you lose control of your private key, MITM attack isn't very difficult.

**Comment by temporarium** [comment]
I have to admit my knowledge of the subject is rather superficial - I understand the concepts, but have little idea of the implementation...

Having said that, Threema's treatment of the issue comes across as very subjective and reasonable - looking for a "secure balance". Makes me doubt a bit of apps that claim to "have it all" working perfectly.

Anyway, thank you for taking the time to reply.
