### ISSUE TITLE
What are your listing requirements / Why do you list BCM Messenger?

### ISSUE THREAD

**Issue by Mikaela** [Perelandra0x309/secure-im#75]
Hi, your website was linked from https://github.com/privacytoolsIO/privacytools.io/issues/1662#issuecomment-578381531 and I am wondering why is BCM Messenger listed as a secure chat app?

I have some concerns about it, copy-paste of quote of https://github.com/privacytoolsIO/privacytools.io/issues/1641#issuecomment-573358373:

> I am not looking into this further at the moment, but my previous comment from #1059:
> 
> > I am worried about it being a "blockchain based messenger" which by definition means that all messages are stored forever and are also publicly available just waiting for the day, its encryption can be broken.
> > The privacy policy also doesn't reassure me, I am not going to register an account without seeing it.
> > > Q: Does BCM have a privacy policy?
> > > You can view our detailed Privacy Policy when registering for a BCM account.
> > 
> > 
> > > Q: Will BCM open source?
> > > BCM is planning to open source, and we will gradually disclose source code of BCM to the public.
> > 
> > 
> > ```
> > * https://bcm-im.com/keys_faq/index.html
> > ```
> > 
> > 
> > Please request reopening after at least these two issues are fixed, Telegram has also been promising open sourcing their server for years.

>     * BCM appears to be unavailable through F-Droid. [bcmapp/bcm-android#2](https://github.com/bcmapp/bcm-android/issues/2)
> 
>     * Their git repository is as poor quality as Telegram Android.  https://github.com/bcmapp/bcm-android/commits/master , they appear to use `git commit` as `git tag` so I don't think anyone can reasonably audit their code, especially if they are going to keep up doing changes of over a thousand line in one commit.
>       
>       * They have a link to iOS app, where is its source code?
> 
>     * Their download page has MD5 checksum (broken ages ago) https://bcm.social/download.html while SHA1 (which is a step up) has been broken recently too. They also haven't signed the hashsum that I can see.
> 
> 
> I am not going to read their privacy policy right now, but I recommend avoiding BCM and not listing them on PrivacyTools. Based on all the times I have looked into it, I advice waiting for them to get an indepedent security audit before considering listing them again.

**Comment by Perelandra0x309** [comment]
Hi Mikaela,
Thanks for alerting me to the link.  I can answer and clear up some things in the PTIO issue.  But to answer your question about why BCM is listed, please refer to my review of the app here:
https://securechatguide.org/decentralizedapps.html#bcm

My listing requirements are essentially: Do I use it myself? Do I feel comfortable using the app for my own private communications.

Having a strict set of requirements that I always apply to every app is difficult, because the requirements depend on your threat model and what information you are trying to protect.  For example, if I always set a requirement that a phone number must not be required then that would exclude Signal as a recommendation.  However I feel Signal is a perfectly secure method of communication with people who would already know your phone number, like friends and family.

For the above reasons, I segmented my favorites recommendations into 4 levels (see https://securechatguide.org/favorites.html).  These are maybe more of what you are asking as each level does have certain criteria that they must meet.
Level 1: Beginner
Level 2: More anonymous, but centralized
Level 3: Peer to Peer or Decentralized
Level 4: Alternative Networks

Yes I could perhaps provide a bit more explanation for each, this page is a work in progress as I just completely redid it a month ago.

At the bottom you will see a chart on how I calculated the scores for each of the 4 categories.  This may be the closest thing to your inquiry about requirements.  Higher scores in each category is better.  No specific feature is necessarily "required" but it is the overall combination of features that establishes my comfort at making a final recommendation.  I see this as an application of the "Defense in depth" strategy in information security.

I hope I answered some of your questions.

**Comment by Mikaela** [comment]
Thank you for your answers
