### ISSUE TITLE
messenger conion.im

### ISSUE THREAD

**Issue by steve4561** [Perelandra0x309/secure-im#83]
Review and comment
website: https://conion.im/

**Comment by Perelandra0x309** [comment]
Do you have any experience or comments on this app?

Looking at the website home page I suspected it was just a XMPP server app.  Then looking at the screenshots confirms this is basically a fork of Conversations.  So this app is really just:
-An XMPP app cloned from Conversations
-Fixed to use their conion.im server as your account server
-Connecting to the server over Tor

All of the above you can already do with the standard Conversations app on Android.  But you can choose your own server.  Also I would be concerned that fixes to the Conversations app would take time to make it into this build.

Who is this group, where are they based?  I cannot find this info.  The website has poor English so they are not native speakers.  The privacy page is incomplete:
https://conion.im/index.php/privacy-policy/

The blog looks like all the entries came with the default Wordpress install, and they are getting nonsense comment spam.

They have an icon for the iOS App store but no link.  So do they plan to build Conversations of iOS as well because that would be quite a feat.

Ok looking at the Android sore entry they do at least give credit to Daniel Gultsch's Conversations there.

I would say stay away, I don't know who is running this server and if we can trust them.  Calling this the "most secure messenger" is a stretch given the amount of meta data the server has access to.

**Comment by steve4561** [comment]
Review and comment
website: https://www.linphone.org/

**Comment by steve4561** [comment]
> Do you have any experience or comments on this app?
> 
> Looking at the website home page I suspected it was just a XMPP server app. Then looking at the screenshots confirms this is basically a fork of Conversations. So this app is really just:
> -An XMPP app cloned from Conversations
> -Fixed to use their conion.im server as your account server
> -Connecting to the server over Tor
> 
> All of the above you can already do with the standard Conversations app on Android. But you can choose your own server. Also I would be concerned that fixes to the Conversations app would take time to make it into this build.
> 
> Who is this group, where are they based? I cannot find this info. The website has poor English so they are not native speakers. The privacy page is incomplete:
> https://conion.im/index.php/privacy-policy/
> 
> The blog looks like all the entries came with the default Wordpress install, and they are getting nonsense comment spam.
> 
> They have an icon for the iOS App store but no link. So do they plan to build Conversations of iOS as well because that would be quite a feat.
> 
> Ok looking at the Android sore entry they do at least give credit to Daniel Gultsch's Conversations there.
> 
> I would say stay away, I don't know who is running this server and if we can trust them. Calling this the "most secure messenger" is a stretch given the amount of meta data the server has access to.

I have no idea
Those who are security expert comment

**Comment by steve4561** [comment]
> Review and comment
> website: https://www.linphone.org/

Also check this messenger
