### ISSUE TITLE
Add silence.im to its own category

### ISSUE THREAD

**Issue by John3** [Perelandra0x309/secure-im#89]
The silence app is SMS/MMS is lower that any other recommended apps, should not be "Highly Recommended",  at least remove the plus, to "Worth a Try". Silence.im only encrypt the messages everything else is plain text and don't protect you for surveillance. 

Anyway just my opinion, I'm not saying it's bad, but should be removed from the recommended section and move it to its own category SMS, or add a field inside the featuresmatrix to show the app is SMS, or inside "Infrastructure"

- https://securechatguide.org/p2papps.html#silence

EDIT: I forgot to mention silence.im is unmaintained

**Comment by Perelandra0x309** [comment]
I think it's similar to XMPP, the message text is encrypted but lots of meta data is not.

But I think you are right the app isn't maintained anymore (wow ha it been 3 years since my last update??)

Merge requests stopeed about a year ago:
https://git.silence.dev/Silence/Silence-Android/-/merge_requests?scope=all&utf8=%E2%9C%93&state=all

Two years ago they moved to their own Gitlab:
https://silence.im/contribute/

**Comment by Perelandra0x309** [comment]
Downgraded to worth a try and noted it appears unmaintained.
